pipeline{
    agent any
    tools{
    maven 'Maven'
    jdk 'jdk'
    }
        
        stages{
            stage('Git-Checkout')
            {
              steps{
                     git 'https://github.com/sreelakshmi665/SonarQube/SonarQubePipeLine'
                }
            }
             stage('Clean')
        {
            steps{
              sh 'mvn clean'
            }
        }
             stage('Validate')
        {
            steps{
              sh 'mvn validate'
            }
        }
        stage('Compile')
        {
            steps{
               sh 'mvn compile'
            }
        }
             stage('Sonar Analysis'){
            steps{
                withSonarQubeEnv('sonar-server'){
                    withMaven(maven:'Maven'){
                        bat 'mvn sonar:sonar'
                    }
                }
            }

        }
        stage('Test')
        {
            steps{
                sh 'mvn test'
            }
        }
        stage('Package')
        {
            steps{
               sh 'mvn package'
            }
        }
        stage('Verify')
        {
            steps{
               sh 'mvn verify'
            }
        }
        stage('Install')
        {
            steps{
                sh 'mvn install'
            }
        }
            
            
           
        }
}
